name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies (Backend)
      working-directory: ./Server
      run: |
        npm install

    - name: Run tests (Backend)
      working-directory: ./Server
      run: |
        npm test

    - name: Install dependencies (Frontend)
      working-directory: ./todo-app
      run: |
        npm install

    - name: Run tests (Frontend)
      working-directory: ./todo-app
      run: |
        npm test

    - name: Build Backend Docker image
      working-directory: ./Server
      run: |
        docker build -t todo-backend .

    - name: Build Frontend Docker image
      working-directory: ./todo-app
      run: |
        docker build -t todo-frontend .

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Kubernetes CLI (kubectl)
      run: |
        curl -LO https://github.com/kubernetes/kubernetes/releases/download/v1.23.0/kubernetes-client-linux-amd64.tar.gz
        tar -xzvf kubernetes-client-linux-amd64.tar.gz
        sudo mv kubernetes/client/bin/kubectl /usr/local/bin

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/backend-deployment.yaml
        kubectl apply -f kubernetes/frontend-deployment.yaml
        kubectl apply -f kubernetes/backend-service.yaml
        kubectl apply -f kubernetes/frontend-service.yaml

